// source: support.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

import jspb, { Message, BinaryReader, BinaryWriter } from 'google-protobuf';
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

goog.exportSymbol('proto.LaptopSupport.DriverInfo', null, global);
goog.exportSymbol('proto.LaptopSupport.Error', null, global);
goog.exportSymbol('proto.LaptopSupport.InstallAppsRequest', null, global);
goog.exportSymbol('proto.LaptopSupport.InstallEnvironmentRequest', null, global);
goog.exportSymbol('proto.LaptopSupport.ProgressUpdate', null, global);
goog.exportSymbol('proto.LaptopSupport.ProgressUpdate.Status', null, global);
goog.exportSymbol('proto.LaptopSupport.QuerySystemInfoRequest', null, global);
goog.exportSymbol('proto.LaptopSupport.RunCommandRequest', null, global);
goog.exportSymbol('proto.LaptopSupport.RunCommandResponse', null, global);
goog.exportSymbol('proto.LaptopSupport.StorageDevice', null, global);
goog.exportSymbol('proto.LaptopSupport.SystemInfoResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.LaptopSupport.InstallAppsRequest = function(opt_data) {
  Message.initialize(this, opt_data, 0, -1, proto.LaptopSupport.InstallAppsRequest.repeatedFields_, null);
};
goog.inherits(proto.LaptopSupport.InstallAppsRequest, Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.LaptopSupport.InstallAppsRequest.displayName = 'proto.LaptopSupport.InstallAppsRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.LaptopSupport.InstallEnvironmentRequest = function(opt_data) {
  Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.LaptopSupport.InstallEnvironmentRequest, Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.LaptopSupport.InstallEnvironmentRequest.displayName = 'proto.LaptopSupport.InstallEnvironmentRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.LaptopSupport.QuerySystemInfoRequest = function(opt_data) {
  Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.LaptopSupport.QuerySystemInfoRequest, Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.LaptopSupport.QuerySystemInfoRequest.displayName = 'proto.LaptopSupport.QuerySystemInfoRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.LaptopSupport.SystemInfoResponse = function(opt_data) {
  Message.initialize(this, opt_data, 0, -1, proto.LaptopSupport.SystemInfoResponse.repeatedFields_, null);
};
goog.inherits(proto.LaptopSupport.SystemInfoResponse, Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.LaptopSupport.SystemInfoResponse.displayName = 'proto.LaptopSupport.SystemInfoResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.LaptopSupport.StorageDevice = function(opt_data) {
  Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.LaptopSupport.StorageDevice, Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.LaptopSupport.StorageDevice.displayName = 'proto.LaptopSupport.StorageDevice';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.LaptopSupport.DriverInfo = function(opt_data) {
  Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.LaptopSupport.DriverInfo, Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.LaptopSupport.DriverInfo.displayName = 'proto.LaptopSupport.DriverInfo';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.LaptopSupport.RunCommandRequest = function(opt_data) {
  Message.initialize(this, opt_data, 0, -1, proto.LaptopSupport.RunCommandRequest.repeatedFields_, null);
};
goog.inherits(proto.LaptopSupport.RunCommandRequest, Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.LaptopSupport.RunCommandRequest.displayName = 'proto.LaptopSupport.RunCommandRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.LaptopSupport.RunCommandResponse = function(opt_data) {
  Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.LaptopSupport.RunCommandResponse, Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.LaptopSupport.RunCommandResponse.displayName = 'proto.LaptopSupport.RunCommandResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.LaptopSupport.ProgressUpdate = function(opt_data) {
  Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.LaptopSupport.ProgressUpdate, Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.LaptopSupport.ProgressUpdate.displayName = 'proto.LaptopSupport.ProgressUpdate';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.LaptopSupport.Error = function(opt_data) {
  Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.LaptopSupport.Error, Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.LaptopSupport.Error.displayName = 'proto.LaptopSupport.Error';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.LaptopSupport.InstallAppsRequest.repeatedFields_ = [1];



if (Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.LaptopSupport.InstallAppsRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.LaptopSupport.InstallAppsRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.LaptopSupport.InstallAppsRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.LaptopSupport.InstallAppsRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
appIdsList: (f = Message.getRepeatedField(msg, 1)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.LaptopSupport.InstallAppsRequest}
 */
proto.LaptopSupport.InstallAppsRequest.deserializeBinary = function(bytes) {
  var reader = new BinaryReader(bytes);
  var msg = new proto.LaptopSupport.InstallAppsRequest;
  return proto.LaptopSupport.InstallAppsRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.LaptopSupport.InstallAppsRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.LaptopSupport.InstallAppsRequest}
 */
proto.LaptopSupport.InstallAppsRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.addAppIds(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.LaptopSupport.InstallAppsRequest.prototype.serializeBinary = function() {
  var writer = new BinaryWriter();
  proto.LaptopSupport.InstallAppsRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.LaptopSupport.InstallAppsRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.LaptopSupport.InstallAppsRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAppIdsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      1,
      f
    );
  }
};


/**
 * repeated string app_ids = 1;
 * @return {!Array<string>}
 */
proto.LaptopSupport.InstallAppsRequest.prototype.getAppIdsList = function() {
  return /** @type {!Array<string>} */ (Message.getRepeatedField(this, 1));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.LaptopSupport.InstallAppsRequest} returns this
 */
proto.LaptopSupport.InstallAppsRequest.prototype.setAppIdsList = function(value) {
  return Message.setField(this, 1, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.LaptopSupport.InstallAppsRequest} returns this
 */
proto.LaptopSupport.InstallAppsRequest.prototype.addAppIds = function(value, opt_index) {
  return Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.LaptopSupport.InstallAppsRequest} returns this
 */
proto.LaptopSupport.InstallAppsRequest.prototype.clearAppIdsList = function() {
  return this.setAppIdsList([]);
};





if (Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.LaptopSupport.InstallEnvironmentRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.LaptopSupport.InstallEnvironmentRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.LaptopSupport.InstallEnvironmentRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.LaptopSupport.InstallEnvironmentRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
environmentId: Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.LaptopSupport.InstallEnvironmentRequest}
 */
proto.LaptopSupport.InstallEnvironmentRequest.deserializeBinary = function(bytes) {
  var reader = new BinaryReader(bytes);
  var msg = new proto.LaptopSupport.InstallEnvironmentRequest;
  return proto.LaptopSupport.InstallEnvironmentRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.LaptopSupport.InstallEnvironmentRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.LaptopSupport.InstallEnvironmentRequest}
 */
proto.LaptopSupport.InstallEnvironmentRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setEnvironmentId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.LaptopSupport.InstallEnvironmentRequest.prototype.serializeBinary = function() {
  var writer = new BinaryWriter();
  proto.LaptopSupport.InstallEnvironmentRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.LaptopSupport.InstallEnvironmentRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.LaptopSupport.InstallEnvironmentRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEnvironmentId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string environment_id = 1;
 * @return {string}
 */
proto.LaptopSupport.InstallEnvironmentRequest.prototype.getEnvironmentId = function() {
  return /** @type {string} */ (Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.LaptopSupport.InstallEnvironmentRequest} returns this
 */
proto.LaptopSupport.InstallEnvironmentRequest.prototype.setEnvironmentId = function(value) {
  return Message.setProto3StringField(this, 1, value);
};





if (Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.LaptopSupport.QuerySystemInfoRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.LaptopSupport.QuerySystemInfoRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.LaptopSupport.QuerySystemInfoRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.LaptopSupport.QuerySystemInfoRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
includeDrivers: Message.getBooleanFieldWithDefault(msg, 1, false),
includeGpuInfo: Message.getBooleanFieldWithDefault(msg, 2, false),
includeStorageInfo: Message.getBooleanFieldWithDefault(msg, 3, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.LaptopSupport.QuerySystemInfoRequest}
 */
proto.LaptopSupport.QuerySystemInfoRequest.deserializeBinary = function(bytes) {
  var reader = new BinaryReader(bytes);
  var msg = new proto.LaptopSupport.QuerySystemInfoRequest;
  return proto.LaptopSupport.QuerySystemInfoRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.LaptopSupport.QuerySystemInfoRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.LaptopSupport.QuerySystemInfoRequest}
 */
proto.LaptopSupport.QuerySystemInfoRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIncludeDrivers(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIncludeGpuInfo(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIncludeStorageInfo(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.LaptopSupport.QuerySystemInfoRequest.prototype.serializeBinary = function() {
  var writer = new BinaryWriter();
  proto.LaptopSupport.QuerySystemInfoRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.LaptopSupport.QuerySystemInfoRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.LaptopSupport.QuerySystemInfoRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getIncludeDrivers();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = message.getIncludeGpuInfo();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getIncludeStorageInfo();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
};


/**
 * optional bool include_drivers = 1;
 * @return {boolean}
 */
proto.LaptopSupport.QuerySystemInfoRequest.prototype.getIncludeDrivers = function() {
  return /** @type {boolean} */ (Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.LaptopSupport.QuerySystemInfoRequest} returns this
 */
proto.LaptopSupport.QuerySystemInfoRequest.prototype.setIncludeDrivers = function(value) {
  return Message.setProto3BooleanField(this, 1, value);
};


/**
 * optional bool include_gpu_info = 2;
 * @return {boolean}
 */
proto.LaptopSupport.QuerySystemInfoRequest.prototype.getIncludeGpuInfo = function() {
  return /** @type {boolean} */ (Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.LaptopSupport.QuerySystemInfoRequest} returns this
 */
proto.LaptopSupport.QuerySystemInfoRequest.prototype.setIncludeGpuInfo = function(value) {
  return Message.setProto3BooleanField(this, 2, value);
};


/**
 * optional bool include_storage_info = 3;
 * @return {boolean}
 */
proto.LaptopSupport.QuerySystemInfoRequest.prototype.getIncludeStorageInfo = function() {
  return /** @type {boolean} */ (Message.getBooleanFieldWithDefault(this, 3, false));
};


/**
 * @param {boolean} value
 * @return {!proto.LaptopSupport.QuerySystemInfoRequest} returns this
 */
proto.LaptopSupport.QuerySystemInfoRequest.prototype.setIncludeStorageInfo = function(value) {
  return Message.setProto3BooleanField(this, 3, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.LaptopSupport.SystemInfoResponse.repeatedFields_ = [5,6];



if (Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.LaptopSupport.SystemInfoResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.LaptopSupport.SystemInfoResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.LaptopSupport.SystemInfoResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.LaptopSupport.SystemInfoResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
cpuName: Message.getFieldWithDefault(msg, 1, ""),
ramTotalGb: Message.getFieldWithDefault(msg, 2, ""),
gpuName: Message.getFieldWithDefault(msg, 3, ""),
osVersion: Message.getFieldWithDefault(msg, 4, ""),
storageDevicesList: Message.toObjectList(msg.getStorageDevicesList(),
    proto.LaptopSupport.StorageDevice.toObject, includeInstance),
driversList: Message.toObjectList(msg.getDriversList(),
    proto.LaptopSupport.DriverInfo.toObject, includeInstance),
error: (f = msg.getError()) && proto.LaptopSupport.Error.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.LaptopSupport.SystemInfoResponse}
 */
proto.LaptopSupport.SystemInfoResponse.deserializeBinary = function(bytes) {
  var reader = new BinaryReader(bytes);
  var msg = new proto.LaptopSupport.SystemInfoResponse;
  return proto.LaptopSupport.SystemInfoResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.LaptopSupport.SystemInfoResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.LaptopSupport.SystemInfoResponse}
 */
proto.LaptopSupport.SystemInfoResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setCpuName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setRamTotalGb(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setGpuName(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setOsVersion(value);
      break;
    case 5:
      var value = new proto.LaptopSupport.StorageDevice;
      reader.readMessage(value,proto.LaptopSupport.StorageDevice.deserializeBinaryFromReader);
      msg.addStorageDevices(value);
      break;
    case 6:
      var value = new proto.LaptopSupport.DriverInfo;
      reader.readMessage(value,proto.LaptopSupport.DriverInfo.deserializeBinaryFromReader);
      msg.addDrivers(value);
      break;
    case 7:
      var value = new proto.LaptopSupport.Error;
      reader.readMessage(value,proto.LaptopSupport.Error.deserializeBinaryFromReader);
      msg.setError(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.LaptopSupport.SystemInfoResponse.prototype.serializeBinary = function() {
  var writer = new BinaryWriter();
  proto.LaptopSupport.SystemInfoResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.LaptopSupport.SystemInfoResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.LaptopSupport.SystemInfoResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCpuName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getRamTotalGb();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getGpuName();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getOsVersion();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getStorageDevicesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      proto.LaptopSupport.StorageDevice.serializeBinaryToWriter
    );
  }
  f = message.getDriversList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      6,
      f,
      proto.LaptopSupport.DriverInfo.serializeBinaryToWriter
    );
  }
  f = message.getError();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      proto.LaptopSupport.Error.serializeBinaryToWriter
    );
  }
};


/**
 * optional string cpu_name = 1;
 * @return {string}
 */
proto.LaptopSupport.SystemInfoResponse.prototype.getCpuName = function() {
  return /** @type {string} */ (Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.LaptopSupport.SystemInfoResponse} returns this
 */
proto.LaptopSupport.SystemInfoResponse.prototype.setCpuName = function(value) {
  return Message.setProto3StringField(this, 1, value);
};


/**
 * optional string ram_total_gb = 2;
 * @return {string}
 */
proto.LaptopSupport.SystemInfoResponse.prototype.getRamTotalGb = function() {
  return /** @type {string} */ (Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.LaptopSupport.SystemInfoResponse} returns this
 */
proto.LaptopSupport.SystemInfoResponse.prototype.setRamTotalGb = function(value) {
  return Message.setProto3StringField(this, 2, value);
};


/**
 * optional string gpu_name = 3;
 * @return {string}
 */
proto.LaptopSupport.SystemInfoResponse.prototype.getGpuName = function() {
  return /** @type {string} */ (Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.LaptopSupport.SystemInfoResponse} returns this
 */
proto.LaptopSupport.SystemInfoResponse.prototype.setGpuName = function(value) {
  return Message.setProto3StringField(this, 3, value);
};


/**
 * optional string os_version = 4;
 * @return {string}
 */
proto.LaptopSupport.SystemInfoResponse.prototype.getOsVersion = function() {
  return /** @type {string} */ (Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.LaptopSupport.SystemInfoResponse} returns this
 */
proto.LaptopSupport.SystemInfoResponse.prototype.setOsVersion = function(value) {
  return Message.setProto3StringField(this, 4, value);
};


/**
 * repeated StorageDevice storage_devices = 5;
 * @return {!Array<!proto.LaptopSupport.StorageDevice>}
 */
proto.LaptopSupport.SystemInfoResponse.prototype.getStorageDevicesList = function() {
  return /** @type{!Array<!proto.LaptopSupport.StorageDevice>} */ (
    Message.getRepeatedWrapperField(this, proto.LaptopSupport.StorageDevice, 5));
};


/**
 * @param {!Array<!proto.LaptopSupport.StorageDevice>} value
 * @return {!proto.LaptopSupport.SystemInfoResponse} returns this
*/
proto.LaptopSupport.SystemInfoResponse.prototype.setStorageDevicesList = function(value) {
  return Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.LaptopSupport.StorageDevice=} opt_value
 * @param {number=} opt_index
 * @return {!proto.LaptopSupport.StorageDevice}
 */
proto.LaptopSupport.SystemInfoResponse.prototype.addStorageDevices = function(opt_value, opt_index) {
  return Message.addToRepeatedWrapperField(this, 5, opt_value, proto.LaptopSupport.StorageDevice, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.LaptopSupport.SystemInfoResponse} returns this
 */
proto.LaptopSupport.SystemInfoResponse.prototype.clearStorageDevicesList = function() {
  return this.setStorageDevicesList([]);
};


/**
 * repeated DriverInfo drivers = 6;
 * @return {!Array<!proto.LaptopSupport.DriverInfo>}
 */
proto.LaptopSupport.SystemInfoResponse.prototype.getDriversList = function() {
  return /** @type{!Array<!proto.LaptopSupport.DriverInfo>} */ (
    Message.getRepeatedWrapperField(this, proto.LaptopSupport.DriverInfo, 6));
};


/**
 * @param {!Array<!proto.LaptopSupport.DriverInfo>} value
 * @return {!proto.LaptopSupport.SystemInfoResponse} returns this
*/
proto.LaptopSupport.SystemInfoResponse.prototype.setDriversList = function(value) {
  return Message.setRepeatedWrapperField(this, 6, value);
};


/**
 * @param {!proto.LaptopSupport.DriverInfo=} opt_value
 * @param {number=} opt_index
 * @return {!proto.LaptopSupport.DriverInfo}
 */
proto.LaptopSupport.SystemInfoResponse.prototype.addDrivers = function(opt_value, opt_index) {
  return Message.addToRepeatedWrapperField(this, 6, opt_value, proto.LaptopSupport.DriverInfo, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.LaptopSupport.SystemInfoResponse} returns this
 */
proto.LaptopSupport.SystemInfoResponse.prototype.clearDriversList = function() {
  return this.setDriversList([]);
};


/**
 * optional Error error = 7;
 * @return {?proto.LaptopSupport.Error}
 */
proto.LaptopSupport.SystemInfoResponse.prototype.getError = function() {
  return /** @type{?proto.LaptopSupport.Error} */ (
    Message.getWrapperField(this, proto.LaptopSupport.Error, 7));
};


/**
 * @param {?proto.LaptopSupport.Error|undefined} value
 * @return {!proto.LaptopSupport.SystemInfoResponse} returns this
*/
proto.LaptopSupport.SystemInfoResponse.prototype.setError = function(value) {
  return Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.LaptopSupport.SystemInfoResponse} returns this
 */
proto.LaptopSupport.SystemInfoResponse.prototype.clearError = function() {
  return this.setError(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.LaptopSupport.SystemInfoResponse.prototype.hasError = function() {
  return Message.getField(this, 7) != null;
};





if (Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.LaptopSupport.StorageDevice.prototype.toObject = function(opt_includeInstance) {
  return proto.LaptopSupport.StorageDevice.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.LaptopSupport.StorageDevice} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.LaptopSupport.StorageDevice.toObject = function(includeInstance, msg) {
  var f, obj = {
model: Message.getFieldWithDefault(msg, 1, ""),
sizeGb: Message.getFieldWithDefault(msg, 2, ""),
freeSpaceGb: Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.LaptopSupport.StorageDevice}
 */
proto.LaptopSupport.StorageDevice.deserializeBinary = function(bytes) {
  var reader = new BinaryReader(bytes);
  var msg = new proto.LaptopSupport.StorageDevice;
  return proto.LaptopSupport.StorageDevice.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.LaptopSupport.StorageDevice} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.LaptopSupport.StorageDevice}
 */
proto.LaptopSupport.StorageDevice.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setModel(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setSizeGb(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setFreeSpaceGb(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.LaptopSupport.StorageDevice.prototype.serializeBinary = function() {
  var writer = new BinaryWriter();
  proto.LaptopSupport.StorageDevice.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.LaptopSupport.StorageDevice} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.LaptopSupport.StorageDevice.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getModel();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getSizeGb();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getFreeSpaceGb();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string model = 1;
 * @return {string}
 */
proto.LaptopSupport.StorageDevice.prototype.getModel = function() {
  return /** @type {string} */ (Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.LaptopSupport.StorageDevice} returns this
 */
proto.LaptopSupport.StorageDevice.prototype.setModel = function(value) {
  return Message.setProto3StringField(this, 1, value);
};


/**
 * optional string size_gb = 2;
 * @return {string}
 */
proto.LaptopSupport.StorageDevice.prototype.getSizeGb = function() {
  return /** @type {string} */ (Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.LaptopSupport.StorageDevice} returns this
 */
proto.LaptopSupport.StorageDevice.prototype.setSizeGb = function(value) {
  return Message.setProto3StringField(this, 2, value);
};


/**
 * optional string free_space_gb = 3;
 * @return {string}
 */
proto.LaptopSupport.StorageDevice.prototype.getFreeSpaceGb = function() {
  return /** @type {string} */ (Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.LaptopSupport.StorageDevice} returns this
 */
proto.LaptopSupport.StorageDevice.prototype.setFreeSpaceGb = function(value) {
  return Message.setProto3StringField(this, 3, value);
};





if (Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.LaptopSupport.DriverInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.LaptopSupport.DriverInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.LaptopSupport.DriverInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.LaptopSupport.DriverInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
deviceName: Message.getFieldWithDefault(msg, 1, ""),
driverVersion: Message.getFieldWithDefault(msg, 2, ""),
status: Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.LaptopSupport.DriverInfo}
 */
proto.LaptopSupport.DriverInfo.deserializeBinary = function(bytes) {
  var reader = new BinaryReader(bytes);
  var msg = new proto.LaptopSupport.DriverInfo;
  return proto.LaptopSupport.DriverInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.LaptopSupport.DriverInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.LaptopSupport.DriverInfo}
 */
proto.LaptopSupport.DriverInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setDeviceName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setDriverVersion(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setStatus(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.LaptopSupport.DriverInfo.prototype.serializeBinary = function() {
  var writer = new BinaryWriter();
  proto.LaptopSupport.DriverInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.LaptopSupport.DriverInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.LaptopSupport.DriverInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDeviceName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getDriverVersion();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getStatus();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string device_name = 1;
 * @return {string}
 */
proto.LaptopSupport.DriverInfo.prototype.getDeviceName = function() {
  return /** @type {string} */ (Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.LaptopSupport.DriverInfo} returns this
 */
proto.LaptopSupport.DriverInfo.prototype.setDeviceName = function(value) {
  return Message.setProto3StringField(this, 1, value);
};


/**
 * optional string driver_version = 2;
 * @return {string}
 */
proto.LaptopSupport.DriverInfo.prototype.getDriverVersion = function() {
  return /** @type {string} */ (Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.LaptopSupport.DriverInfo} returns this
 */
proto.LaptopSupport.DriverInfo.prototype.setDriverVersion = function(value) {
  return Message.setProto3StringField(this, 2, value);
};


/**
 * optional string status = 3;
 * @return {string}
 */
proto.LaptopSupport.DriverInfo.prototype.getStatus = function() {
  return /** @type {string} */ (Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.LaptopSupport.DriverInfo} returns this
 */
proto.LaptopSupport.DriverInfo.prototype.setStatus = function(value) {
  return Message.setProto3StringField(this, 3, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.LaptopSupport.RunCommandRequest.repeatedFields_ = [2];



if (Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.LaptopSupport.RunCommandRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.LaptopSupport.RunCommandRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.LaptopSupport.RunCommandRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.LaptopSupport.RunCommandRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
command: Message.getFieldWithDefault(msg, 1, ""),
argsList: (f = Message.getRepeatedField(msg, 2)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.LaptopSupport.RunCommandRequest}
 */
proto.LaptopSupport.RunCommandRequest.deserializeBinary = function(bytes) {
  var reader = new BinaryReader(bytes);
  var msg = new proto.LaptopSupport.RunCommandRequest;
  return proto.LaptopSupport.RunCommandRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.LaptopSupport.RunCommandRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.LaptopSupport.RunCommandRequest}
 */
proto.LaptopSupport.RunCommandRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setCommand(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.addArgs(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.LaptopSupport.RunCommandRequest.prototype.serializeBinary = function() {
  var writer = new BinaryWriter();
  proto.LaptopSupport.RunCommandRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.LaptopSupport.RunCommandRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.LaptopSupport.RunCommandRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCommand();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getArgsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      2,
      f
    );
  }
};


/**
 * optional string command = 1;
 * @return {string}
 */
proto.LaptopSupport.RunCommandRequest.prototype.getCommand = function() {
  return /** @type {string} */ (Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.LaptopSupport.RunCommandRequest} returns this
 */
proto.LaptopSupport.RunCommandRequest.prototype.setCommand = function(value) {
  return Message.setProto3StringField(this, 1, value);
};


/**
 * repeated string args = 2;
 * @return {!Array<string>}
 */
proto.LaptopSupport.RunCommandRequest.prototype.getArgsList = function() {
  return /** @type {!Array<string>} */ (Message.getRepeatedField(this, 2));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.LaptopSupport.RunCommandRequest} returns this
 */
proto.LaptopSupport.RunCommandRequest.prototype.setArgsList = function(value) {
  return Message.setField(this, 2, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.LaptopSupport.RunCommandRequest} returns this
 */
proto.LaptopSupport.RunCommandRequest.prototype.addArgs = function(value, opt_index) {
  return Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.LaptopSupport.RunCommandRequest} returns this
 */
proto.LaptopSupport.RunCommandRequest.prototype.clearArgsList = function() {
  return this.setArgsList([]);
};





if (Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.LaptopSupport.RunCommandResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.LaptopSupport.RunCommandResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.LaptopSupport.RunCommandResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.LaptopSupport.RunCommandResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
standardOutput: Message.getFieldWithDefault(msg, 1, ""),
standardError: Message.getFieldWithDefault(msg, 2, ""),
exitCode: Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.LaptopSupport.RunCommandResponse}
 */
proto.LaptopSupport.RunCommandResponse.deserializeBinary = function(bytes) {
  var reader = new BinaryReader(bytes);
  var msg = new proto.LaptopSupport.RunCommandResponse;
  return proto.LaptopSupport.RunCommandResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.LaptopSupport.RunCommandResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.LaptopSupport.RunCommandResponse}
 */
proto.LaptopSupport.RunCommandResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setStandardOutput(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setStandardError(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setExitCode(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.LaptopSupport.RunCommandResponse.prototype.serializeBinary = function() {
  var writer = new BinaryWriter();
  proto.LaptopSupport.RunCommandResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.LaptopSupport.RunCommandResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.LaptopSupport.RunCommandResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStandardOutput();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getStandardError();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getExitCode();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
};


/**
 * optional string standard_output = 1;
 * @return {string}
 */
proto.LaptopSupport.RunCommandResponse.prototype.getStandardOutput = function() {
  return /** @type {string} */ (Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.LaptopSupport.RunCommandResponse} returns this
 */
proto.LaptopSupport.RunCommandResponse.prototype.setStandardOutput = function(value) {
  return Message.setProto3StringField(this, 1, value);
};


/**
 * optional string standard_error = 2;
 * @return {string}
 */
proto.LaptopSupport.RunCommandResponse.prototype.getStandardError = function() {
  return /** @type {string} */ (Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.LaptopSupport.RunCommandResponse} returns this
 */
proto.LaptopSupport.RunCommandResponse.prototype.setStandardError = function(value) {
  return Message.setProto3StringField(this, 2, value);
};


/**
 * optional int32 exit_code = 3;
 * @return {number}
 */
proto.LaptopSupport.RunCommandResponse.prototype.getExitCode = function() {
  return /** @type {number} */ (Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.LaptopSupport.RunCommandResponse} returns this
 */
proto.LaptopSupport.RunCommandResponse.prototype.setExitCode = function(value) {
  return Message.setProto3IntField(this, 3, value);
};





if (Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.LaptopSupport.ProgressUpdate.prototype.toObject = function(opt_includeInstance) {
  return proto.LaptopSupport.ProgressUpdate.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.LaptopSupport.ProgressUpdate} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.LaptopSupport.ProgressUpdate.toObject = function(includeInstance, msg) {
  var f, obj = {
currentTask: Message.getFieldWithDefault(msg, 1, ""),
overallPercentage: Message.getFieldWithDefault(msg, 2, 0),
status: Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.LaptopSupport.ProgressUpdate}
 */
proto.LaptopSupport.ProgressUpdate.deserializeBinary = function(bytes) {
  var reader = new BinaryReader(bytes);
  var msg = new proto.LaptopSupport.ProgressUpdate;
  return proto.LaptopSupport.ProgressUpdate.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.LaptopSupport.ProgressUpdate} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.LaptopSupport.ProgressUpdate}
 */
proto.LaptopSupport.ProgressUpdate.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setCurrentTask(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setOverallPercentage(value);
      break;
    case 3:
      var value = /** @type {!proto.LaptopSupport.ProgressUpdate.Status} */ (reader.readEnum());
      msg.setStatus(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.LaptopSupport.ProgressUpdate.prototype.serializeBinary = function() {
  var writer = new BinaryWriter();
  proto.LaptopSupport.ProgressUpdate.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.LaptopSupport.ProgressUpdate} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.LaptopSupport.ProgressUpdate.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCurrentTask();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getOverallPercentage();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getStatus();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.LaptopSupport.ProgressUpdate.Status = {
  UNKNOWN: 0,
  IN_PROGRESS: 1,
  COMPLETED: 2,
  FAILED: 3
};

/**
 * optional string current_task = 1;
 * @return {string}
 */
proto.LaptopSupport.ProgressUpdate.prototype.getCurrentTask = function() {
  return /** @type {string} */ (Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.LaptopSupport.ProgressUpdate} returns this
 */
proto.LaptopSupport.ProgressUpdate.prototype.setCurrentTask = function(value) {
  return Message.setProto3StringField(this, 1, value);
};


/**
 * optional int32 overall_percentage = 2;
 * @return {number}
 */
proto.LaptopSupport.ProgressUpdate.prototype.getOverallPercentage = function() {
  return /** @type {number} */ (Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.LaptopSupport.ProgressUpdate} returns this
 */
proto.LaptopSupport.ProgressUpdate.prototype.setOverallPercentage = function(value) {
  return Message.setProto3IntField(this, 2, value);
};


/**
 * optional Status status = 3;
 * @return {!proto.LaptopSupport.ProgressUpdate.Status}
 */
proto.LaptopSupport.ProgressUpdate.prototype.getStatus = function() {
  return /** @type {!proto.LaptopSupport.ProgressUpdate.Status} */ (Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.LaptopSupport.ProgressUpdate.Status} value
 * @return {!proto.LaptopSupport.ProgressUpdate} returns this
 */
proto.LaptopSupport.ProgressUpdate.prototype.setStatus = function(value) {
  return Message.setProto3EnumField(this, 3, value);
};





if (Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.LaptopSupport.Error.prototype.toObject = function(opt_includeInstance) {
  return proto.LaptopSupport.Error.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.LaptopSupport.Error} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.LaptopSupport.Error.toObject = function(includeInstance, msg) {
  var f, obj = {
code: Message.getFieldWithDefault(msg, 1, ""),
message: Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.LaptopSupport.Error}
 */
proto.LaptopSupport.Error.deserializeBinary = function(bytes) {
  var reader = new BinaryReader(bytes);
  var msg = new proto.LaptopSupport.Error;
  return proto.LaptopSupport.Error.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.LaptopSupport.Error} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.LaptopSupport.Error}
 */
proto.LaptopSupport.Error.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setCode(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setMessage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.LaptopSupport.Error.prototype.serializeBinary = function() {
  var writer = new BinaryWriter();
  proto.LaptopSupport.Error.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.LaptopSupport.Error} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.LaptopSupport.Error.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCode();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getMessage();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string code = 1;
 * @return {string}
 */
proto.LaptopSupport.Error.prototype.getCode = function() {
  return /** @type {string} */ (Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.LaptopSupport.Error} returns this
 */
proto.LaptopSupport.Error.prototype.setCode = function(value) {
  return Message.setProto3StringField(this, 1, value);
};


/**
 * optional string message = 2;
 * @return {string}
 */
proto.LaptopSupport.Error.prototype.getMessage = function() {
  return /** @type {string} */ (Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.LaptopSupport.Error} returns this
 */
proto.LaptopSupport.Error.prototype.setMessage = function(value) {
  return Message.setProto3StringField(this, 2, value);
};


goog.object.extend(exports, proto.LaptopSupport);
